### PR TITLE
Change the default for the dlq to be off by default.

### PR DESCRIPTION
**Pull request by gklijs**
Fixes https://github.com/AxonIQ/console-framework-client/issues/50

### CODE REVIEW

**Comment by abuijze** [comment]
Just wondering, since the concern is that potentially business-specific data is transferred over the wire without explicit permission of the app developers, isn't it sufficient to default to `masked`?

**Comment by gklijs** [comment]
It might be fine to switch to masked as the default. That's not how I interpreted the story through. Maybe @SaraTorrey can decide. I don't know what the worries are. For example, with masked, anyone could still initiate a retry, which might not be something we allow by default.

**Comment by SaraTorrey** [comment]
After discussing various options with Gerard, I think setting the default to `off` is a better option for security and privacy reasons.

**Review by smcvb — APPROVED** [review]
LGTM!
Another question though: wdyt about expanding the setup instructions to clarify the DLQ option is off by default?

**Comment by gklijs** [comment]
I noticed discrepancies in the readme, so I made some adjustments. Hence, asking for a review again.

**Review by smcvb — APPROVED** [review]
Still think this looks fine.

**Pull request merged**
